name: pocketai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  dio: ^5.9.0
  path_provider: ^2.1.5
  record: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
